### ISSUE TITLE
URL looks bigger than actual provided!

### ISSUE THREAD

**Issue by nisargparikh69** [newtoallofthis123/short_cli#1]
As per Snapshot in README file , the url provided is youtube.com and output url is much bigger! does not make sense to call it shortened url !

**Comment by newtoallofthis123** [comment]
I know @nisargparikh69. I never intended NoobShort to be an actual URL shortener. The original [NoobShort](https://noobscience.rocks/go) was just to learn MongoDB and Next.js. It is now ported to Astro and this CLI is just a small wrapper around it.

The url noobscience.rocks I got for free on my student account and plan on renewing it. 

The reason I made nshrt was to learn how to make a good rust cli and I was able to do that. nshrt has made the foundation that helped me build other rust tools like [lyka](https://github.com/newtoallofthis123/lyka_cli).

Thanks for your interest in the project 😄. Please free to contribute.

Moreover, this might be a stretch, but if you know of a way for me to get a shorter url, please let me know.

**Comment by nisargparikh69** [comment]
Cool lemme know if you want any enhancement. I am taking part under hacktoberfest.... I will raise PR and you can approve if you like it

**Comment by newtoallofthis123** [comment]
That's really nice of you @nisargparikh69....I am currently looking for help with documentation, code review and ideas on another rust project I am working on called [evnv](https://github.com/newtoallofthis123/envn)...It is basically a global secrets and `.env` manager. 

I am working on it on my Ubuntu Machine, but I need help testing and debugging it on windows....I have added the Hacktober label to the project. Just search for Todo's in the project comments :)

Thanks!

**Comment by nisargparikh69** [comment]
@newtoallofthis123 Please create issues in evnv project , I would solve bug fix / do enhancement

**Comment by newtoallofthis123** [comment]
Sure 😄

**Comment by newtoallofthis123** [comment]
Hey @nisargparikh69 this is a big one
 https://github.com/newtoallofthis123/envn/issues/1
